const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const tools=require('../order-tools.js');const googleContext=require('./google-mock.cjs');
const ids={admin:'00000000-0000-0000-0000-000000000001',a:'00000000-0000-0000-0000-000000000002',b:'00000000-0000-0000-0000-000000000003',off:'00000000-0000-0000-0000-000000000004'};
const sample=(id='original')=>({id,createdAt:'2026-10-07T12:00:00.000Z',date:'07/10/2026 09:00',client:'Cliente',cnpj:'00',ie:'Isento',buyer:'Pessoa',phone:'27',payment:'Pix',items:[{product:'Mangueira',detail:'50m',meters:50,unitPrice:2,subtotal:100}],gross:100,discountPct:0,discountVal:0,final:100});
const note=(p,value)=>({...p,items:p.items.map(i=>({...i,observation:value}))});
test('Versões: migração preserva pedidos, revisão atômica é autorizada e idempotente, conflito não sobrescreve, renovação é independente',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
   create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
  const migrations=path.join(__dirname,'../supabase/migrations');
  for(const file of fs.readdirSync(migrations).filter(x=>x.endsWith('.sql')&&!x.includes('order_revisions')).sort())await db.exec(fs.readFileSync(path.join(migrations,file),'utf8'));
  for(const [name,id] of Object.entries(ids))await db.query('insert into auth.users values($1,$2,$3)',[id,name+'@example.test',{full_name:name}]);
  await db.query("update public.profiles set active=true where id<>$1",[ids.off]);await db.query("update public.profiles set role='admin' where id=$1",[ids.admin]);
  const original=sample();await db.query('insert into public.orders(id,owner_id,payload) values($1,$2,$3)',['original',ids.a,original]);
  await db.exec(fs.readFileSync(path.join(migrations,'202610070004_order_revisions.sql'),'utf8'));
  assert.deepEqual((await db.query("select payload from public.orders where id='original'")).rows[0].payload,original);
  const as=async(role,id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+role);};
  const first=note(original,'Azul'),request='10000000-0000-0000-0000-000000000001';
  const revise=(payload=first,expected=1,key=request,reason='Cliente solicitou azul')=>db.query('select public.revise_order($1,$2,$3,$4,$5) as result',['original',expected,payload,reason,key]);
  await as('authenticated',ids.b);assert.equal((await db.query('select * from public.order_revisions')).rows.length,0);await assert.rejects(()=>revise(),/sem permissão/);
  await assert.rejects(()=>db.query('insert into public.orders(id,owner_id,payload) values($1,$2,$3)',['forged',ids.b,{...sample('forged'),renewedFromId:'original'}]),/indisponível/);
  await as('authenticated',ids.off);await assert.rejects(()=>revise(),/Acesso não liberado/);
  await as('anon');await assert.rejects(()=>revise(),/permission denied/);
  await as('authenticated',ids.a);
  await assert.rejects(()=>db.query("update public.orders set payload=payload where id='original'"),/permission denied/);
  await assert.rejects(()=>db.query("delete from public.order_revisions where order_id='original'"),/permission denied/);
  await assert.rejects(()=>db.query('insert into public.orders(id,owner_id,payload,revision) values($1,$2,$3,5)',['fake',ids.a,sample('fake')]),/permission denied/);
  for(const bad of [note(original,42),note(original,'a'.repeat(501)),{...first,date:'08/10/2026'},{...first,id:'other'}])await assert.rejects(()=>revise(bad),/Dados inválidos/);
  assert.equal((await revise()).rows[0].result.revision,2);
  assert.equal((await revise()).rows[0].result.revision,2,'retry does not create another version');
  assert.equal((await db.query("select * from public.order_revisions where order_id='original'")).rows.length,2);
  await assert.rejects(()=>revise(note(original,'Verde'),1,'10000000-0000-0000-0000-000000000002'),/outro aparelho/);
  await assert.rejects(()=>revise(note(original,'Verde'),1,request),/outros dados/);
  await as('authenticated',ids.admin);
  const second=note(first,'Verde');await revise(second,2,'10000000-0000-0000-0000-000000000003','Cliente solicitou verde');
  const state=(await db.query("select owner_id,revision,google_state from public.orders where id='original'")).rows[0];
  assert.deepEqual(state,{owner_id:ids.a,revision:3,google_state:'not_sent'});
  const versions=(await db.query("select revision,payload,editor_name,reason from public.order_revisions where order_id='original' order by revision")).rows;
  assert.equal(versions[0].payload.items[0].observation,undefined);assert.equal(versions[1].payload.items[0].observation,'Azul');assert.equal(versions[2].payload.items[0].observation,'Verde');assert.equal(versions[2].editor_name,'admin');
  await as('authenticated',ids.a);
  const renewal={...second,id:'renewed',createdAt:'2026-10-08T12:00:00Z',date:'08/10/2026 09:00',renewedFromId:'original'};
  await db.query('insert into public.orders(id,owner_id,payload) values($1,$2,$3)',['renewed',ids.a,renewal]);
  assert.equal((await db.query("select count(*)::int as count from public.orders")).rows[0].count,2);
  assert.equal((await db.query("select revision from public.orders where id='renewed'")).rows[0].revision,1);
  assert.equal((await db.query("select reason from public.order_revisions where order_id='renewed'")).rows[0].reason,'Renovação de pedido');
  assert.deepEqual((await db.query("select payload from public.orders where id='original'")).rows[0].payload,second);
 }finally{await db.close();}
});
test('Google atualiza a mesma guia, mantém filtros e seleção, não aceita versão antiga e reaproveita uma revisão parcial',()=>{
 const mock=googleContext();const original=sample();const send=orders=>mock.context.syncOrders({version:1,orders});
 assert.equal(send([original]).ok,true);const summary=mock.spreadsheet.getSheetByName('Consulta de pedidos');summary.getRange('A7').setValue(true);summary.getFilter().setColumnFilterCriteria(4,{query:'Cliente'});
 const revised={...note(original,'=Cor azul'),revision:2};const result=send([revised]);assert.equal(result.ok,true);
 assert.equal(mock.sheets.length,3);const sheet=mock.sheets[2];assert.equal(sheet.getCell(13,6),"'=Cor azul");assert.match(sheet.getCell(2,1),/Versão 2/);
 assert.equal(summary.getCell(7,1),true);assert.equal(summary.getFilter().getColumnFilterCriteria(4).query,'Cliente');
 assert.equal(result.orderRevisions[0].revision,2);assert.equal(send([original]).ok,false);assert.equal(sheet.getCell(13,6),"'=Cor azul");
 const newer={...note(original,'Verde'),revision:3};mock.fail=call=>call.sheet===sheet.name&&call.method==='setValues'&&call.address[0]===13;
 assert.equal(send([newer]).ok,false);mock.fail=null;assert.equal(send([newer]).ok,true);assert.equal(mock.sheets.length,3);assert.equal(sheet.getCell(13,6),'Verde');
 assert.equal(send([{...newer,id:'renewed',renewedFromId:'original'}]).ok,true);assert.equal(mock.sheets.length,4);
 const count=mock.calls.length;assert.equal(send([newer]).ok,true);assert.ok(mock.calls.slice(count).every(c=>c.sheet!==sheet.name),'same version never rewrites its sheet');
});
test('Observações aparecem na busca, HTML escapado, CSV e diferenças entre versões',()=>{
 const before=sample(),after=note(before,'Azul <img src=x>\nSomente esta cor');
 assert.equal(tools.matches(after,'azul'),true);const html=tools.printHtml({...after,revision:2});assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img'));assert.match(html,/Versão 2/);
 assert.ok(tools.csv([after]).includes('Observação: Azul'));assert.ok(tools.changes(before,after).some(c=>c.includes('observação')));
 assert.equal(tools.payload({...after,ownerId:'spoof',revision:99}).ownerId,undefined);
});
